"""Pull request management — creation, review, merge automation."""

import asyncio
from typing import Any

import structlog

logger = structlog.get_logger()


PR_TEMPLATE = """## Summary
{summary}

## Changes
{changes}

## Related Issues
{issues}

## Testing
{testing}

## Coverage
{coverage}
"""


class PRManager:
    """Creates, reviews, and merges pull requests."""

    def __init__(self, repo: str = "") -> None:
        self.repo = repo

    async def _run_gh(self, args: str) -> tuple[int, str, str]:
        cmd = f"gh {args}"
        if self.repo:
            cmd += f" --repo {self.repo}"
        proc = await asyncio.create_subprocess_shell(
            cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=30)
        return proc.returncode, stdout.decode(), stderr.decode()

    async def create_pr(
        self,
        title: str,
        head: str,
        base: str,
        summary: str = "",
        changes: str = "",
        issues: str = "",
        testing: str = "",
        coverage: str = "",
    ) -> dict[str, Any]:
        """Create a PR with auto-filled template."""
        body = PR_TEMPLATE.format(
            summary=summary or "Auto-generated by agent",
            changes=changes or "See diff",
            issues=issues or "None",
            testing=testing or "Tests included",
            coverage=coverage or "See coverage report",
        )
        safe_body = body.replace('"', '\\"').replace("\n", "\\n")
        code, out, err = await self._run_gh(
            f'pr create --title "{title}" --body "{safe_body}" --head {head} --base {base}'
        )
        if code != 0:
            logger.error("pr_creation_failed", title=title, error=err)
            return {"created": False, "error": err}

        # Parse PR number from URL
        pr_number = None
        try:
            pr_number = int(out.strip().split("/")[-1])
        except (ValueError, IndexError):
            pass

        logger.info("pr_created", title=title, head=head, base=base, pr=pr_number)
        return {"created": True, "pr_number": pr_number, "url": out.strip()}

    async def review_pr(
        self, pr_number: int, action: str, body: str = ""
    ) -> dict[str, Any]:
        """Post a review on a PR. action: approve | request_changes | comment."""
        flag_map = {
            "approve": "--approve",
            "request_changes": "--request-changes",
            "comment": "--comment",
        }
        flag = flag_map.get(action, "--comment")
        safe_body = body.replace('"', '\\"') if body else "Review by Code Reviewer agent"
        code, out, err = await self._run_gh(
            f'pr review {pr_number} {flag} --body "{safe_body}"'
        )
        if code != 0:
            return {"reviewed": False, "error": err}
        logger.info("pr_reviewed", pr=pr_number, action=action)
        return {"reviewed": True, "action": action}

    async def merge_pr(self, pr_number: int, method: str = "squash") -> dict[str, Any]:
        """Merge a PR. method: merge | squash | rebase."""
        code, out, err = await self._run_gh(
            f"pr merge {pr_number} --{method} --delete-branch"
        )
        if code != 0:
            logger.error("pr_merge_failed", pr=pr_number, error=err)
            return {"merged": False, "error": err}
        logger.info("pr_merged", pr=pr_number, method=method)
        return {"merged": True}

    async def get_pr_diff(self, pr_number: int) -> str:
        """Fetch the diff for a PR."""
        code, out, err = await self._run_gh(f"pr diff {pr_number}")
        if code != 0:
            return f"Error fetching diff: {err}"
        return out

    async def list_pr_files(self, pr_number: int) -> list[str]:
        """List files changed in a PR."""
        code, out, err = await self._run_gh(f"pr view {pr_number} --json files --jq '.files[].path'")
        if code != 0:
            return []
        return [f.strip() for f in out.strip().split("\n") if f.strip()]
